apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
    - port: 5672        # Port for internal communication (AMQP)
      targetPort: 5672
      name: amqp
    - port: 15672       # Port for the management UI
      targetPort: 15672
      name: management
  selector:
    app: rabbitmq
  type: ClusterIP
