apiVersion: apps/v1
kind: Deployment
metadata:
  name: matching-service
  labels:
    app: matching-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: matching-service
  template:
    metadata:
      labels:
        app: matching-service
    spec:
      containers:
        - name: matching-service
          image: us-central1-docker.pkg.dev/eastern-shell-439115-p7/peerprep-repo/matching-service:v4
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              value: "8002"
            - name: LOCAL_RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: COLLAB_SERVICE_URL
              value: "http://collaboration-service:8003"
      restartPolicy: Always
