apiVersion: v1
kind: Service
metadata:
  name: collaboration-service
spec:
  type: ClusterIP
  ports:
    - port: 8003
      targetPort: 8003
      protocol: TCP
  selector:
    app: collaboration-service